[package]
name = "surrealdb_test_jason05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
surrealdb = "1.0.0-beta.7"
tokio = {version = "1.21.1", features=["full"]}
